CREATE COLUMN TABLE "LIVE4"."VBAP" ("MANDT" NVARCHAR(3) DEFAULT '000' NOT NULL ,
	 "VBELN" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "POSNR" NVARCHAR(6) DEFAULT '000000' NOT NULL ,
	 "MATNR" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "MATWA" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "PMATN" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "CHARG" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "MATKL" NVARCHAR(9) DEFAULT '' NOT NULL ,
	 "ARKTX" NVARCHAR(40) DEFAULT '' NOT NULL ,
	 "PSTYV" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "POSAR" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "LFREL" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "FKREL" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "UEPOS" NVARCHAR(6) DEFAULT '000000' NOT NULL ,
	 "GRPOS" NVARCHAR(6) DEFAULT '000000' NOT NULL ,
	 "ABGRU" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "PRODH" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "ZWERT" DECIMAL(13,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "ZMENG" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "ZIEME" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "UMZIZ" DECIMAL(5,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "UMZIN" DECIMAL(5,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "MEINS" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "SMENG" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "ABLFZ" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "ABDAT" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "ABSFZ" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "POSEX" NVARCHAR(6) DEFAULT '' NOT NULL ,
	 "KDMAT" NVARCHAR(35) DEFAULT '' NOT NULL ,
	 "KBVER" DECIMAL(3,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KEVER" DECIMAL(3,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VKGRU" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "VKAUS" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "GRKOR" NVARCHAR(3) DEFAULT '000' NOT NULL ,
	 "FMENG" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "UEBTK" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "UEBTO" DECIMAL(3,
	1) CS_FIXED DEFAULT 0 NOT NULL ,
	 "UNTTO" DECIMAL(3,
	1) CS_FIXED DEFAULT 0 NOT NULL ,
	 "FAKSP" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "ATPKZ" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "RKFKF" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "SPART" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "GSBER" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "NETWR" DECIMAL(15,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "WAERK" NVARCHAR(5) DEFAULT '' NOT NULL ,
	 "ANTLF" DECIMAL(1,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KZTLF" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "CHSPL" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "KWMENG" DECIMAL(15,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "LSMENG" DECIMAL(15,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KBMENG" DECIMAL(15,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KLMENG" DECIMAL(15,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VRKME" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "UMVKZ" DECIMAL(5,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "UMVKN" DECIMAL(5,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "BRGEW" DECIMAL(15,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "NTGEW" DECIMAL(15,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "GEWEI" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "VOLUM" DECIMAL(15,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VOLEH" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "VBELV" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "POSNV" NVARCHAR(6) DEFAULT '000000' NOT NULL ,
	 "VGBEL" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "VGPOS" NVARCHAR(6) DEFAULT '000000' NOT NULL ,
	 "VOREF" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "UPFLU" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "ERLRE" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "LPRIO" NVARCHAR(2) DEFAULT '00' NOT NULL ,
	 "WERKS" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "LGORT" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "VSTEL" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "ROUTE" NVARCHAR(6) DEFAULT '' NOT NULL ,
	 "STKEY" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "STDAT" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "STLNR" NVARCHAR(8) DEFAULT '' NOT NULL ,
	 "STPOS" DECIMAL(5,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "AWAHR" NVARCHAR(3) DEFAULT '000' NOT NULL ,
	 "ERDAT" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "ERNAM" NVARCHAR(12) DEFAULT '' NOT NULL ,
	 "ERZET" NVARCHAR(6) DEFAULT '000000' NOT NULL ,
	 "TAXM1" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "TAXM2" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "TAXM3" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "TAXM4" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "TAXM5" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "TAXM6" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "TAXM7" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "TAXM8" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "TAXM9" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "VBEAF" DECIMAL(5,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VBEAV" DECIMAL(5,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VGREF" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "NETPR" DECIMAL(11,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KPEIN" DECIMAL(5,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KMEIN" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "SHKZG" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "SKTOF" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "MTVFP" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "SUMBD" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "KONDM" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "KTGRM" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "BONUS" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "PROVG" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "EANNR" NVARCHAR(13) DEFAULT '' NOT NULL ,
	 "PRSOK" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "BWTAR" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "BWTEX" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "XCHPF" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "XCHAR" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "LFMNG" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "STAFO" NVARCHAR(6) DEFAULT '' NOT NULL ,
	 "WAVWR" DECIMAL(13,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KZWI1" DECIMAL(13,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KZWI2" DECIMAL(13,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KZWI3" DECIMAL(13,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KZWI4" DECIMAL(13,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KZWI5" DECIMAL(13,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KZWI6" DECIMAL(13,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "STCUR" DECIMAL(9,
	5) CS_FIXED DEFAULT 0 NOT NULL ,
	 "AEDAT" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "EAN11" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "FIXMG" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "PRCTR" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "MVGR1" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "MVGR2" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "MVGR3" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "MVGR4" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "MVGR5" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "KMPMG" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "SUGRD" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "SOBKZ" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "VPZUO" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "PAOBJNR" NVARCHAR(10) DEFAULT '0000000000' NOT NULL ,
	 "PS_PSP_PNR" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "AUFNR" NVARCHAR(12) DEFAULT '' NOT NULL ,
	 "VPMAT" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "VPWRK" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "PRBME" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "UMREF" DOUBLE CS_DOUBLE DEFAULT 0 NOT NULL ,
	 "KNTTP" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "KZVBR" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "SERNR" NVARCHAR(8) DEFAULT '' NOT NULL ,
	 "OBJNR" NVARCHAR(22) DEFAULT '' NOT NULL ,
	 "ABGRS" NVARCHAR(6) DEFAULT '' NOT NULL ,
	 "BEDAE" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "CMPRE" DECIMAL(11,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "CMTFG" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "CMPNT" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "CMKUA" DECIMAL(9,
	5) CS_FIXED DEFAULT 0 NOT NULL ,
	 "CUOBJ" NVARCHAR(18) DEFAULT '000000000000000000' NOT NULL ,
	 "CUOBJ_CH" NVARCHAR(18) DEFAULT '000000000000000000' NOT NULL ,
	 "CEPOK" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "KOUPD" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "SERAIL" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "ANZSN" INTEGER CS_INT DEFAULT 0 NOT NULL ,
	 "NACHL" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "MAGRV" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "MPROK" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "VGTYP" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "PROSA" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "UEPVW" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "KALNR" NVARCHAR(12) DEFAULT '000000000000' NOT NULL ,
	 "KLVAR" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "SPOSN" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "KOWRR" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "STADAT" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "EXART" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "PREFE" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "KNUMH" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "CLINT" NVARCHAR(10) DEFAULT '0000000000' NOT NULL ,
	 "CHMVS" NVARCHAR(3) DEFAULT '000' NOT NULL ,
	 "STLTY" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "STLKN" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "STPOZ" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "STMAN" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "ZSCHL_K" NVARCHAR(6) DEFAULT '' NOT NULL ,
	 "KALSM_K" NVARCHAR(6) DEFAULT '' NOT NULL ,
	 "KALVAR" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "KOSCH" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "UPMAT" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "UKONM" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "MFRGR" NVARCHAR(8) DEFAULT '' NOT NULL ,
	 "PLAVO" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "KANNR" NVARCHAR(35) DEFAULT '' NOT NULL ,
	 "CMPRE_FLT" DOUBLE CS_DOUBLE DEFAULT 0 NOT NULL ,
	 "ABFOR" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "ABGES" DOUBLE CS_DOUBLE DEFAULT 0 NOT NULL ,
	 "J_1BCFOP" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "J_1BTAXLW1" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "J_1BTAXLW2" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "J_1BTXSDC" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "WKTNR" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "WKTPS" NVARCHAR(6) DEFAULT '000000' NOT NULL ,
	 "SKOPF" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "KZBWS" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "WGRU1" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "WGRU2" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "KNUMA_PI" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "KNUMA_AG" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "KZFME" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "LSTANR" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "TECHS" NVARCHAR(12) DEFAULT '' NOT NULL ,
	 "MWSBP" DECIMAL(13,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "BERID" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "PCTRF" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "LOGSYS_EXT" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "J_1BTAXLW3" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "J_1BTAXLW4" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "J_1BTAXLW5" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "STOCKLOC" NVARCHAR(20) DEFAULT '' NOT NULL ,
	 "SLOCTYPE" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "MSR_RET_REASON" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "MSR_REFUND_CODE" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "MSR_APPROV_BLOCK" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "NRAB_KNUMH" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "TRMRISK_RELEVANT" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "SGT_RCAT" NVARCHAR(16) DEFAULT '' NOT NULL ,
	 "HANDOVERLOC" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "HANDOVERDATE" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "HANDOVERTIME" NVARCHAR(6) DEFAULT '000000' NOT NULL ,
	 "TC_AUT_DET" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "MANUAL_TC_REASON" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "FISCAL_INCENTIVE" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "TAX_SUBJECT_ST" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "FISCAL_INCENTIVE_ID" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "SPCSTO" NVARCHAR(2) DEFAULT '00' NOT NULL ,
	 "_DATAAGING" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "/BEV1/SRFUND" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "AUFPL_OLC" NVARCHAR(10) DEFAULT '0000000000' NOT NULL ,
	 "APLZL_OLC" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "FERC_IND" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "FSH_SEASON_YEAR" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "FSH_SEASON" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "FSH_COLLECTION" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "FSH_THEME" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "FSH_CRSD" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "FSH_SEAREF" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "FSH_CANDATE" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "FSH_VAS_REL" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "FSH_VAS_PRNT_ID" NVARCHAR(6) DEFAULT '000000' NOT NULL ,
	 "FSH_TRANSACTION" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "FSH_ITEM_GROUP" NVARCHAR(5) DEFAULT '00000' NOT NULL ,
	 "FSH_ITEM" NVARCHAR(5) DEFAULT '00000' NOT NULL ,
	 "FSH_VASREF" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "KOSTL" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "FONDS" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "FISTL" NVARCHAR(16) DEFAULT '' NOT NULL ,
	 "FKBER" NVARCHAR(16) DEFAULT '' NOT NULL ,
	 "GRANT_NBR" NVARCHAR(20) DEFAULT '' NOT NULL ,
	 "BUDGET_PD" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "IUID_RELEVANT" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "MILL_SE_GPOSN" NVARCHAR(6) DEFAULT '000000' NOT NULL ,
	 "PRS_OBJNR" NVARCHAR(22) DEFAULT '' NOT NULL ,
	 "PRS_SD_SPSNR" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "PRS_WORK_PERIOD" NVARCHAR(7) DEFAULT '0000000' NOT NULL ,
	 "TAS" NVARCHAR(30) DEFAULT '' NOT NULL ,
	 "BETC" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "MOD_ALLOW" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "CANCEL_ALLOW" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "PAY_METHOD" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "BPN" NVARCHAR(6) DEFAULT '' NOT NULL ,
	 "REP_FREQ" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "FMFGUS_KEY" NVARCHAR(22) DEFAULT '' NOT NULL ,
	 "PARGB" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "AUFPL_OAA" NVARCHAR(10) DEFAULT '0000000000' NOT NULL ,
	 "APLZL_OAA" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "ARSNUM" NVARCHAR(10) DEFAULT '0000000000' NOT NULL ,
	 "ARSPOS" NVARCHAR(4) DEFAULT '0000' NOT NULL ,
	 "WTYSC_CLMITEM" NVARCHAR(16) DEFAULT '' NOT NULL ,
	 PRIMARY KEY ("MANDT",
	 "VBELN",
	 "POSNR")) UNLOAD PRIORITY 5 AUTO MERGE 
;
COMMENT ON TABLE "LIVE4"."VBAP" is 'Sales Document: Item Data'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MANDT" is 'Client'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VBELN" is 'Sales Document'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."POSNR" is 'Sales Document Item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MATNR" is 'Material Number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MATWA" is 'Material entered'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PMATN" is 'Pricing Reference Material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CHARG" is 'Batch Number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MATKL" is 'Material Group'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ARKTX" is 'Short text for sales order item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PSTYV" is 'Sales document item category'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."POSAR" is 'Item type'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."LFREL" is 'Item is relevant for delivery'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FKREL" is 'Relevant for Billing'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UEPOS" is 'Higher-level item in bill of material structures'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."GRPOS" is 'Item for which this item is an alternative'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ABGRU" is 'Reason for rejection of quotations and sales orders'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PRODH" is 'Product hierarchy'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ZWERT" is 'Target Value for Outline Agreement in Document Currency'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ZMENG" is 'Target quantity in sales units'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ZIEME" is 'Target quantity UoM'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UMZIZ" is 'Factor for converting sales units to base units (target qty)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UMZIN" is 'Factor for converting sales units to base units (target qty)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MEINS" is 'Base Unit of Measure'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SMENG" is 'Scale quantity in base unit of measure'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ABLFZ" is 'Rounding quantity for delivery'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ABDAT" is 'Reconciliation date for agreed cumulative quantity'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ABSFZ" is 'Allowed deviation in quantity (absolute)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."POSEX" is 'Item Number of the Underlying Purchase Order'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KDMAT" is 'Material Number Used by Customer'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KBVER" is 'Allowed deviation in quantity (in percent)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KEVER" is 'Days by which the quantity can be shifted'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VKGRU" is 'Repair Processing: Classification of Items'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VKAUS" is 'Usage Indicator'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."GRKOR" is 'Delivery group (items are delivered together)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FMENG" is 'Quantity is fixed'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UEBTK" is 'Unlimited overdelivery allowed'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UEBTO" is 'Overdelivery Tolerance Limit'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UNTTO" is 'Underdelivery Tolerance Limit'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FAKSP" is 'Billing block for item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ATPKZ" is 'Replacement part'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."RKFKF" is 'Method of billing for CO/PPC orders'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SPART" is 'Division'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."GSBER" is 'Business Area'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."NETWR" is 'Net value of the order item in document currency'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."WAERK" is 'SD document currency'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ANTLF" is 'Maximum Number of Partial Deliveries Allowed Per Item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KZTLF" is 'Partial delivery at item level'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CHSPL" is 'Batch split allowed'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KWMENG" is 'Cumulative order quantity in sales units'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."LSMENG" is 'Cumulative required delivery qty (all dlv-relev.sched.lines)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KBMENG" is 'Cumulative confirmed quantity in sales unit'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KLMENG" is 'Cumulative confirmed quantity in base unit'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VRKME" is 'Sales unit'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UMVKZ" is 'Numerator (factor) for conversion of sales quantity into SKU'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UMVKN" is 'Denominator (Divisor) for Conversion of Sales Qty into SKU'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."BRGEW" is 'Gross Weight of the Item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."NTGEW" is 'Net Weight of the Item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."GEWEI" is 'Weight Unit'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VOLUM" is 'Volume of the item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VOLEH" is 'Volume unit'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VBELV" is 'Originating document'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."POSNV" is 'Originating item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VGBEL" is 'Document number of the reference document'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VGPOS" is 'Item number of the reference item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VOREF" is 'Complete reference indicator'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UPFLU" is 'Update indicator for sales document document flow'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ERLRE" is 'Completion rule for quotation / contract'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."LPRIO" is 'Delivery Priority'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."WERKS" is 'Plant (Own or External)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."LGORT" is 'Storage location'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VSTEL" is 'Shipping Point/Receiving Point'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ROUTE" is 'Route'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STKEY" is 'Origin of the bill of material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STDAT" is 'Key date of the bill of material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STLNR" is 'Bill of material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STPOS" is 'Bill of material item number VBAP not used'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."AWAHR" is 'Order probability of the item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ERDAT" is 'Date on which the record was created'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ERNAM" is 'Name of Person who Created the Object'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ERZET" is 'Entry time'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TAXM1" is 'Tax classification material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TAXM2" is 'Tax classification material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TAXM3" is 'Tax classification material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TAXM4" is 'Tax classification material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TAXM5" is 'Tax classification material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TAXM6" is 'Tax classification material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TAXM7" is 'Tax classification material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TAXM8" is 'Tax classification material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TAXM9" is 'Tax classification material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VBEAF" is 'Fixed shipping processing time in days (= setup time)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VBEAV" is 'Variable shipping processing time in days'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VGREF" is 'Preceding document has resulted from reference'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."NETPR" is 'Net price'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KPEIN" is 'Condition pricing unit'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KMEIN" is 'Condition unit'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SHKZG" is 'Returns Item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SKTOF" is 'Cash discount indicator'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MTVFP" is 'Checking Group for Availability Check'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SUMBD" is 'Summing up of requirements'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KONDM" is 'Material Pricing Group'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KTGRM" is 'Account assignment group for this material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."BONUS" is 'Volume rebate group'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PROVG" is 'Commission group'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."EANNR" is 'European Article Number (EAN) - obsolete!!!!!'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PRSOK" is 'Pricing is OK'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."BWTAR" is 'Valuation type'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."BWTEX" is 'Indicator: Separate valuation'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."XCHPF" is 'Batch management requirement indicator'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."XCHAR" is 'Batch management indicator (internal)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."LFMNG" is 'Minimum delivery quantity in delivery note processing'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STAFO" is 'Update group for statistics update'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."WAVWR" is 'Cost in document currency'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KZWI1" is 'Subtotal 1 from pricing procedure for condition'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KZWI2" is 'Subtotal 2 from pricing procedure for condition'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KZWI3" is 'Subtotal 3 from pricing procedure for condition'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KZWI4" is 'Subtotal 4 from pricing procedure for condition'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KZWI5" is 'Subtotal 5 from pricing procedure for condition'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KZWI6" is 'Subtotal 6 from pricing procedure for condition'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STCUR" is 'Exchange rate for statistics (Exch.rate at time of creation)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."AEDAT" is 'Changed On'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."EAN11" is 'International Article Number (EAN/UPC)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FIXMG" is 'Delivery date and quantity fixed'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PRCTR" is 'Profit Center'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MVGR1" is 'Material group 1'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MVGR2" is 'Material group 2'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MVGR3" is 'Material group 3'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MVGR4" is 'Material group 4'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MVGR5" is 'Material group 5'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KMPMG" is 'Component quantity'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SUGRD" is 'Reason for material substitution'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SOBKZ" is 'Special Stock Indicator'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VPZUO" is 'Allocation Indicator'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PAOBJNR" is 'Profitability Segment Number (CO-PA)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PS_PSP_PNR" is 'Work Breakdown Structure Element (WBS Element)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."AUFNR" is 'Order Number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VPMAT" is 'Planning material'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VPWRK" is 'Planning plant'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PRBME" is 'Base unit of measure for product group'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UMREF" is 'Conversion factor: quantities'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KNTTP" is 'Account assignment category'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KZVBR" is 'Consumption posting'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SERNR" is 'BOM explosion number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."OBJNR" is 'Object number at item level'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ABGRS" is 'Results Analysis Key'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."BEDAE" is 'Requirements type'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CMPRE" is 'Item credit price'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CMTFG" is 'ID for partial release of order item, credit block'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CMPNT" is 'ID: Item with active credit function / relevant for credit'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CMKUA" is 'Credit data exchange rate for requested delivery date'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CUOBJ" is 'Configuration'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CUOBJ_CH" is 'Internal object number of the batch classification'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CEPOK" is 'Status expected price'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KOUPD" is 'Condition update'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SERAIL" is 'Serial Number Profile'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ANZSN" is 'Number of serial numbers'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."NACHL" is 'Customer has not posted goods receipt'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MAGRV" is 'Material Group: Packaging Materials'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MPROK" is 'Status manual price change'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."VGTYP" is 'Document category of preceding SD document'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PROSA" is 'ID for material determination'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UEPVW" is 'ID for higher-level item usage'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KALNR" is 'Cost Estimate Number for Cost Est. w/o Qty Structure'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KLVAR" is 'Costing Variant'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SPOSN" is 'BOM Item Number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KOWRR" is 'Statistical values'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STADAT" is 'Statistics date'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."EXART" is 'Business Transaction Type for Foreign Trade'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PREFE" is 'Preference indicator in export/import'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KNUMH" is 'Number of condition record from batch determination'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CLINT" is 'Internal Class Number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CHMVS" is 'Batches: Exit to quantity proposal'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STLTY" is 'BOM category'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STLKN" is 'BOM item node number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STPOZ" is 'Internal counter'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STMAN" is 'Inconsistent configuration'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ZSCHL_K" is 'Overhead key'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KALSM_K" is 'Costing Sheet'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KALVAR" is 'Costing Variant'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KOSCH" is 'Product allocation determination procedure'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UPMAT" is 'Pricing reference material of main item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."UKONM" is 'Material pricing group of main item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MFRGR" is 'Material freight group'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PLAVO" is 'Planning delivery schedule instruction'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KANNR" is 'KANBAN/sequence number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CMPRE_FLT" is 'Item credit price'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ABFOR" is 'Form of payment guarantee'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ABGES" is 'Guaranteed (factor between 0 and 1)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."J_1BCFOP" is 'CFOP Code and Extension'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."J_1BTAXLW1" is 'Tax law: ICMS'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."J_1BTAXLW2" is 'Tax law: IPI'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."J_1BTXSDC" is 'SD tax code'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."WKTNR" is 'Value contract no.'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."WKTPS" is 'Value contract item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SKOPF" is 'Assortment module'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KZBWS" is 'Valuation of Special Stock'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."WGRU1" is 'Material group hierarchy 1'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."WGRU2" is 'Material group hierarchy 2'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KNUMA_PI" is 'Promotion'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KNUMA_AG" is 'Sales deal'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KZFME" is 'ID: Leading unit of measure for completing a transaction'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."LSTANR" is 'Free goods delivery control'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TECHS" is 'Parameter Variant/Standard Variant'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MWSBP" is 'Tax amount in document currency'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."BERID" is 'MRP Area'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PCTRF" is 'Profit Center for Billing'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."LOGSYS_EXT" is 'Logical System'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."J_1BTAXLW3" is 'ISS Tax Law'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."J_1BTAXLW4" is 'COFINS Tax Law'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."J_1BTAXLW5" is 'PIS Tax Law'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."STOCKLOC" is 'First Inventory-Managing Location'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SLOCTYPE" is 'Type of First Inventory-Managing Location'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MSR_RET_REASON" is 'Return Reason'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MSR_REFUND_CODE" is 'Returns Refund Code'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MSR_APPROV_BLOCK" is 'Approval Block'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."NRAB_KNUMH" is 'Condition record number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TRMRISK_RELEVANT" is 'Risk Relevancy in Sales'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SGT_RCAT" is 'Requirement Segment'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."HANDOVERLOC" is 'Location for a physical handover of goods'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."HANDOVERDATE" is 'Handover Date at the Handover Location'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."HANDOVERTIME" is 'Handover time at the handover location'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TC_AUT_DET" is 'Tax Code Automatically Determined'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MANUAL_TC_REASON" is 'Manual Tax Code Reason'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FISCAL_INCENTIVE" is 'Tax Incentive Type'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TAX_SUBJECT_ST" is 'Tax Subject to Substituição Tributária'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FISCAL_INCENTIVE_ID" is 'Incentive ID'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."SPCSTO" is 'Nota Fiscal Special Case for CFOP Determination'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."_DATAAGING" is 'Data Filter Value for Data Aging'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."/BEV1/SRFUND" is 'Analysis/Reason for Rejection'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."AUFPL_OLC" is 'Routing number of operations in the order'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."APLZL_OLC" is 'Internal counter'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FERC_IND" is 'Regulatory indicator'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_SEASON_YEAR" is 'Season Year'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_SEASON" is 'Season'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_COLLECTION" is 'Fashion Collection'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_THEME" is 'Fashion Theme'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_CRSD" is 'Condition Record Number for Seasons'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_SEAREF" is 'Season Determined from Reference Document'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_CANDATE" is 'Item Cancellation Date'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_VAS_REL" is 'VAS Relevant'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_VAS_PRNT_ID" is 'Item number of the SD document'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_TRANSACTION" is 'Transaction Number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_ITEM_GROUP" is 'Item Group'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_ITEM" is 'Item Number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FSH_VASREF" is 'VAS Determined from Reference Document'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."KOSTL" is 'Cost Center'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FONDS" is 'Fund'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FISTL" is 'Funds Center'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FKBER" is 'Functional Area'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."GRANT_NBR" is 'Grant'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."BUDGET_PD" is 'FM: Budget Period'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."IUID_RELEVANT" is 'IUID Relevant for Customer'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MILL_SE_GPOSN" is 'Global Item'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PRS_OBJNR" is 'Engagement mgmt: Object number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PRS_SD_SPSNR" is 'Standard WBS Element for Project Inception via SD'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PRS_WORK_PERIOD" is 'Work Period (Internal Representation)'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."TAS" is 'Treasury Account Symbol'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."BETC" is 'Business Event Type Code'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."MOD_ALLOW" is 'Modification Allowed'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."CANCEL_ALLOW" is 'Cancellation Allowed'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PAY_METHOD" is 'List of Respected Payment Methods'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."BPN" is 'Business Partner Number'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."REP_FREQ" is 'Reporting Frequency'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."FMFGUS_KEY" is 'United States Federal Government Fields'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."PARGB" is 'Trading partner''s business area'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."AUFPL_OAA" is 'Routing number of operations in the order'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."APLZL_OAA" is 'Internal counter'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ARSNUM" is 'Number of reservation/dependent requirements'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."ARSPOS" is 'Item number of reservation/dependent requirements'
;
COMMENT ON COLUMN "LIVE4"."VBAP"."WTYSC_CLMITEM" is 'Claim item number'
;

-----------
-- T100W --
-----------

CREATE COLUMN TABLE "LIVE4"."T001W" ("MANDT" NVARCHAR(3) DEFAULT '000' NOT NULL ,
	 "WERKS" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "NAME1" NVARCHAR(30) DEFAULT '' NOT NULL ,
	 "BWKEY" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "KUNNR" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "LIFNR" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "FABKL" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "NAME2" NVARCHAR(30) DEFAULT '' NOT NULL ,
	 "STRAS" NVARCHAR(30) DEFAULT '' NOT NULL ,
	 "PFACH" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "PSTLZ" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "ORT01" NVARCHAR(25) DEFAULT '' NOT NULL ,
	 "EKORG" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "VKORG" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "CHAZV" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "KKOWK" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "KORDB" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "BEDPL" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "LAND1" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "REGIO" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "COUNC" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "CITYC" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "ADRNR" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "IWERK" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "TXJCD" NVARCHAR(15) DEFAULT '' NOT NULL ,
	 "VTWEG" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "SPART" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "SPRAS" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "WKSOP" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "AWSLS" NVARCHAR(6) DEFAULT '' NOT NULL ,
	 "CHAZV_OLD" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "VLFKZ" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "BZIRK" NVARCHAR(6) DEFAULT '' NOT NULL ,
	 "ZONE1" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "TAXIW" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "BZQHL" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "LET01" DECIMAL(3,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "LET02" DECIMAL(3,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "LET03" DECIMAL(3,
	0) CS_FIXED DEFAULT 0 NOT NULL ,
	 "TXNAM_MA1" NVARCHAR(16) DEFAULT '' NOT NULL ,
	 "TXNAM_MA2" NVARCHAR(16) DEFAULT '' NOT NULL ,
	 "TXNAM_MA3" NVARCHAR(16) DEFAULT '' NOT NULL ,
	 "BETOL" NVARCHAR(3) DEFAULT '000' NOT NULL ,
	 "J_1BBRANCH" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "VTBFI" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "FPRFW" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "ACHVM" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "DVSART" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "NODETYPE" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "NSCHEMA" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "PKOSA" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "MISCH" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "MGVUPD" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "VSTEL" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "MGVLAUPD" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "MGVLAREVAL" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "SOURCING" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "FSH_MG_ARUN_REQ" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "FSH_SEAIM" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "OILIVAL" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "OIHVTYPE" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "OIHCREDIPI" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "STORETYPE" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "DEP_STORE" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 PRIMARY KEY ("MANDT",
	 "WERKS")) UNLOAD PRIORITY 5 AUTO MERGE 
;
COMMENT ON TABLE "LIVE4"."T001W" is 'Plants/Branches'
;
COMMENT ON COLUMN "LIVE4"."T001W"."MANDT" is 'Client'
;
COMMENT ON COLUMN "LIVE4"."T001W"."WERKS" is 'Plant'
;
COMMENT ON COLUMN "LIVE4"."T001W"."NAME1" is 'Name'
;
COMMENT ON COLUMN "LIVE4"."T001W"."BWKEY" is 'Valuation area'
;
COMMENT ON COLUMN "LIVE4"."T001W"."KUNNR" is 'Customer number of plant'
;
COMMENT ON COLUMN "LIVE4"."T001W"."LIFNR" is 'Vendor number of plant'
;
COMMENT ON COLUMN "LIVE4"."T001W"."FABKL" is 'Factory calendar key'
;
COMMENT ON COLUMN "LIVE4"."T001W"."NAME2" is 'Name 2'
;
COMMENT ON COLUMN "LIVE4"."T001W"."STRAS" is 'Street and House Number'
;
COMMENT ON COLUMN "LIVE4"."T001W"."PFACH" is 'PO Box'
;
COMMENT ON COLUMN "LIVE4"."T001W"."PSTLZ" is 'Postal Code'
;
COMMENT ON COLUMN "LIVE4"."T001W"."ORT01" is 'City'
;
COMMENT ON COLUMN "LIVE4"."T001W"."EKORG" is 'Purchasing organization'
;
COMMENT ON COLUMN "LIVE4"."T001W"."VKORG" is 'Sales organization for intercompany billing'
;
COMMENT ON COLUMN "LIVE4"."T001W"."CHAZV" is 'Indicator: batch status management active'
;
COMMENT ON COLUMN "LIVE4"."T001W"."KKOWK" is 'Indicator: Conditions at plant level'
;
COMMENT ON COLUMN "LIVE4"."T001W"."KORDB" is 'Indicator: Source list requirement'
;
COMMENT ON COLUMN "LIVE4"."T001W"."BEDPL" is 'Activating requirements planning'
;
COMMENT ON COLUMN "LIVE4"."T001W"."LAND1" is 'Country Key'
;
COMMENT ON COLUMN "LIVE4"."T001W"."REGIO" is 'Region (State, Province, County)'
;
COMMENT ON COLUMN "LIVE4"."T001W"."COUNC" is 'County Code'
;
COMMENT ON COLUMN "LIVE4"."T001W"."CITYC" is 'City Code'
;
COMMENT ON COLUMN "LIVE4"."T001W"."ADRNR" is 'Address'
;
COMMENT ON COLUMN "LIVE4"."T001W"."IWERK" is 'Maintenance Planning Plant'
;
COMMENT ON COLUMN "LIVE4"."T001W"."TXJCD" is 'Tax Jurisdiction'
;
COMMENT ON COLUMN "LIVE4"."T001W"."VTWEG" is 'Distribution channel for intercompany billing'
;
COMMENT ON COLUMN "LIVE4"."T001W"."SPART" is 'Division for intercompany billing'
;
COMMENT ON COLUMN "LIVE4"."T001W"."SPRAS" is 'Language Key'
;
COMMENT ON COLUMN "LIVE4"."T001W"."WKSOP" is 'SOP plant'
;
COMMENT ON COLUMN "LIVE4"."T001W"."AWSLS" is 'Variance Key'
;
COMMENT ON COLUMN "LIVE4"."T001W"."CHAZV_OLD" is 'Indicator: batch status management active'
;
COMMENT ON COLUMN "LIVE4"."T001W"."VLFKZ" is 'Plant category'
;
COMMENT ON COLUMN "LIVE4"."T001W"."BZIRK" is 'Sales district'
;
COMMENT ON COLUMN "LIVE4"."T001W"."ZONE1" is 'Supply region (region supplied)'
;
COMMENT ON COLUMN "LIVE4"."T001W"."TAXIW" is 'Tax Indicator: Plant (Purchasing)'
;
COMMENT ON COLUMN "LIVE4"."T001W"."BZQHL" is 'Take regular vendor into account'
;
COMMENT ON COLUMN "LIVE4"."T001W"."LET01" is 'Number of Days for First Reminder/Expediter'
;
COMMENT ON COLUMN "LIVE4"."T001W"."LET02" is 'Number of Days for Second Reminder/Expediter'
;
COMMENT ON COLUMN "LIVE4"."T001W"."LET03" is 'Number of Days for Third Reminder/Expediter'
;
COMMENT ON COLUMN "LIVE4"."T001W"."TXNAM_MA1" is 'Text name of 1st dunning of vendor declarations'
;
COMMENT ON COLUMN "LIVE4"."T001W"."TXNAM_MA2" is 'Text name of the 2nd dunning of vendor declarations'
;
COMMENT ON COLUMN "LIVE4"."T001W"."TXNAM_MA3" is 'Text name of 3rd dunning of vendor declarations'
;
COMMENT ON COLUMN "LIVE4"."T001W"."BETOL" is 'Number of days for PO tolerance - Compress info records - SU'
;
COMMENT ON COLUMN "LIVE4"."T001W"."J_1BBRANCH" is 'Business Place'
;
COMMENT ON COLUMN "LIVE4"."T001W"."VTBFI" is 'Rule for determining the sales area for stock transfers'
;
COMMENT ON COLUMN "LIVE4"."T001W"."FPRFW" is 'Distribution profile at plant level'
;
COMMENT ON COLUMN "LIVE4"."T001W"."ACHVM" is 'Central archiving marker for master record'
;
COMMENT ON COLUMN "LIVE4"."T001W"."DVSART" is 'Batch Record: Type of DMS Used'
;
COMMENT ON COLUMN "LIVE4"."T001W"."NODETYPE" is 'Node type: supply chain network'
;
COMMENT ON COLUMN "LIVE4"."T001W"."NSCHEMA" is 'Structure for name formation'
;
COMMENT ON COLUMN "LIVE4"."T001W"."PKOSA" is 'Cost Object Controlling linking active'
;
COMMENT ON COLUMN "LIVE4"."T001W"."MISCH" is 'Updating is active for mixed costing'
;
COMMENT ON COLUMN "LIVE4"."T001W"."MGVUPD" is 'Updating is active in actual costing'
;
COMMENT ON COLUMN "LIVE4"."T001W"."VSTEL" is 'Shipping Point/Receiving Point'
;
COMMENT ON COLUMN "LIVE4"."T001W"."MGVLAUPD" is 'Update of Activity Consumption in the Quantity Structure'
;
COMMENT ON COLUMN "LIVE4"."T001W"."MGVLAREVAL" is 'Control of Credit of Cost Centers'
;
COMMENT ON COLUMN "LIVE4"."T001W"."SOURCING" is 'Invoke Added-Function Source Determination via ATP'
;
COMMENT ON COLUMN "LIVE4"."T001W"."FSH_MG_ARUN_REQ" is 'Order Allocation Run'
;
COMMENT ON COLUMN "LIVE4"."T001W"."FSH_SEAIM" is 'Indicator: Season Active in Inventory Management'
;
COMMENT ON COLUMN "LIVE4"."T001W"."OILIVAL" is 'Exchange valuation indicator'
;
COMMENT ON COLUMN "LIVE4"."T001W"."OIHVTYPE" is 'Vendor type (refinery/mill/other) (Brazil)'
;
COMMENT ON COLUMN "LIVE4"."T001W"."OIHCREDIPI" is 'IPI credit allowed'
;
COMMENT ON COLUMN "LIVE4"."T001W"."STORETYPE" is 'Store Category to Differentiate Store, Dep. Store, Shop'
;
COMMENT ON COLUMN "LIVE4"."T001W"."DEP_STORE" is 'Superior Department Store'
;

----------
-- MARD --
----------

CREATE COLUMN TABLE "LIVE4"."MARD" ("MANDT" NVARCHAR(3) DEFAULT '000' NOT NULL ,
	 "MATNR" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "WERKS" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "LGORT" NVARCHAR(4) DEFAULT '' NOT NULL ,
	 "PSTAT" NVARCHAR(15) DEFAULT '' NOT NULL ,
	 "LVORM" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "LFGJA" NVARCHAR(4) DEFAULT '0000' NOT NULL ,
	 "LFMON" NVARCHAR(2) DEFAULT '00' NOT NULL ,
	 "SPERR" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "LABST" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "UMLME" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "INSME" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "EINME" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "SPEME" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "RETME" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VMLAB" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VMUML" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VMINS" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VMEIN" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VMSPE" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VMRET" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KZILL" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "KZILQ" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "KZILE" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "KZILS" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "KZVLL" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "KZVLQ" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "KZVLE" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "KZVLS" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "DISKZ" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "LSOBS" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "LMINB" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "LBSTF" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "HERKL" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "EXPPG" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "EXVER" NVARCHAR(2) DEFAULT '' NOT NULL ,
	 "LGPBE" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "KLABS" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KINSM" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KEINM" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "KSPEM" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 "DLINL" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "PRCTL" NVARCHAR(10) DEFAULT '' NOT NULL ,
	 "ERSDA" NVARCHAR(8) DEFAULT '00000000' NOT NULL ,
	 "VKLAB" DECIMAL(13,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "VKUML" DECIMAL(13,
	2) CS_FIXED DEFAULT 0 NOT NULL ,
	 "LWMKB" NVARCHAR(3) DEFAULT '' NOT NULL ,
	 "BSKRF" DOUBLE CS_DOUBLE DEFAULT 0 NOT NULL ,
	 "MDRUE" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "MDJIN" NVARCHAR(4) DEFAULT '0000' NOT NULL ,
	 "FSH_SALLOC_QTY_S" DECIMAL(13,
	3) CS_FIXED DEFAULT 0 NOT NULL ,
	 PRIMARY KEY ("MANDT",
	 "MATNR",
	 "WERKS",
	 "LGORT")) UNLOAD PRIORITY 5 AUTO MERGE 
;
COMMENT ON TABLE "LIVE4"."MARD" is 'Storage Location Data for Material'
;
COMMENT ON COLUMN "LIVE4"."MARD"."MANDT" is 'Client'
;
COMMENT ON COLUMN "LIVE4"."MARD"."MATNR" is 'Material Number'
;
COMMENT ON COLUMN "LIVE4"."MARD"."WERKS" is 'Plant'
;
COMMENT ON COLUMN "LIVE4"."MARD"."LGORT" is 'Storage location'
;
COMMENT ON COLUMN "LIVE4"."MARD"."PSTAT" is 'Maintenance status'
;
COMMENT ON COLUMN "LIVE4"."MARD"."LVORM" is 'Flag Material for Deletion at Storage Location Level'
;
COMMENT ON COLUMN "LIVE4"."MARD"."LFGJA" is 'Fiscal Year of Current Period'
;
COMMENT ON COLUMN "LIVE4"."MARD"."LFMON" is 'Current period (posting period)'
;
COMMENT ON COLUMN "LIVE4"."MARD"."SPERR" is 'Physical Inventory Blocking Indicator'
;
COMMENT ON COLUMN "LIVE4"."MARD"."LABST" is 'Valuated Unrestricted-Use Stock'
;
COMMENT ON COLUMN "LIVE4"."MARD"."UMLME" is 'Stock in transfer (from one storage location to another)'
;
COMMENT ON COLUMN "LIVE4"."MARD"."INSME" is 'Stock in Quality Inspection'
;
COMMENT ON COLUMN "LIVE4"."MARD"."EINME" is 'Total Stock of All Restricted Batches'
;
COMMENT ON COLUMN "LIVE4"."MARD"."SPEME" is 'Blocked Stock'
;
COMMENT ON COLUMN "LIVE4"."MARD"."RETME" is 'Blocked Stock Returns'
;
COMMENT ON COLUMN "LIVE4"."MARD"."VMLAB" is 'Valuated unrestricted-use stock in previous period'
;
COMMENT ON COLUMN "LIVE4"."MARD"."VMUML" is 'Stock in Transfer in Previous Period'
;
COMMENT ON COLUMN "LIVE4"."MARD"."VMINS" is 'Stock in Quality Inspection in Previous Period'
;
COMMENT ON COLUMN "LIVE4"."MARD"."VMEIN" is 'Restricted-Use Stock in Previous Period'
;
COMMENT ON COLUMN "LIVE4"."MARD"."VMSPE" is 'Blocked stock of previous period'
;
COMMENT ON COLUMN "LIVE4"."MARD"."VMRET" is 'Blocked Stock Returns in Previous Period'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KZILL" is 'Physical inventory indicator for whse stock in current year'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KZILQ" is 'Phys. inventory ind. f. stock in qual. insp. in current year'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KZILE" is 'Physical inventory indicator for restricted-use stock'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KZILS" is 'Physical inventory indicator for blocked stock'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KZVLL" is 'Physical inventory indicator for stock in previous year'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KZVLQ" is 'Phys. inventory ind. f. stock in qual. insp. in prev. period'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KZVLE" is 'Physical inventory ind. for restricted-use stock, prev.pd'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KZVLS" is 'Phys. inventory indicator for blocked stock in prev. period'
;
COMMENT ON COLUMN "LIVE4"."MARD"."DISKZ" is 'Storage location MRP indicator'
;
COMMENT ON COLUMN "LIVE4"."MARD"."LSOBS" is 'Special procurement type at storage location level'
;
COMMENT ON COLUMN "LIVE4"."MARD"."LMINB" is 'Reorder point for storage location MRP'
;
COMMENT ON COLUMN "LIVE4"."MARD"."LBSTF" is 'Replenishment quantity for storage location MRP'
;
COMMENT ON COLUMN "LIVE4"."MARD"."HERKL" is 'Country of origin of the material'
;
COMMENT ON COLUMN "LIVE4"."MARD"."EXPPG" is 'Preference indicator (deactivated)'
;
COMMENT ON COLUMN "LIVE4"."MARD"."EXVER" is 'Export indicator (deactivated)'
;
COMMENT ON COLUMN "LIVE4"."MARD"."LGPBE" is 'Storage Bin'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KLABS" is 'Unrestricted-Use Consignment Stock'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KINSM" is 'Consignment Stock in Quality Inspection'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KEINM" is 'Restricted-Use Consignment Stock'
;
COMMENT ON COLUMN "LIVE4"."MARD"."KSPEM" is 'Blocked Consignment Stock'
;
COMMENT ON COLUMN "LIVE4"."MARD"."DLINL" is 'Date of Last Posted Count'
;
COMMENT ON COLUMN "LIVE4"."MARD"."PRCTL" is 'Profit Center'
;
COMMENT ON COLUMN "LIVE4"."MARD"."ERSDA" is 'Created On'
;
COMMENT ON COLUMN "LIVE4"."MARD"."VKLAB" is 'Stock value of a value-only material at sales price'
;
COMMENT ON COLUMN "LIVE4"."MARD"."VKUML" is 'Sales value in stock transfer (SLOc to SLoc)'
;
COMMENT ON COLUMN "LIVE4"."MARD"."LWMKB" is 'Picking area for lean WM'
;
COMMENT ON COLUMN "LIVE4"."MARD"."BSKRF" is 'Inventory correction factor'
;
COMMENT ON COLUMN "LIVE4"."MARD"."MDRUE" is 'MARDH rec. already exists for per. before last of MARD per.'
;
COMMENT ON COLUMN "LIVE4"."MARD"."MDJIN" is 'Fiscal year of current physical inventory indicator'
;
COMMENT ON COLUMN "LIVE4"."MARD"."FSH_SALLOC_QTY_S" is 'ARun Stock Allocated Quantity'
;

----------
-- MAKT --
----------

CREATE COLUMN TABLE "LIVE4"."MAKT" ("MANDT" NVARCHAR(3) DEFAULT '000' NOT NULL ,
	 "MATNR" NVARCHAR(18) DEFAULT '' NOT NULL ,
	 "SPRAS" NVARCHAR(1) DEFAULT '' NOT NULL ,
	 "MAKTX" NVARCHAR(40) DEFAULT '' NOT NULL ,
	 "MAKTG" NVARCHAR(40) DEFAULT '' NOT NULL ,
	 PRIMARY KEY ("MANDT",
	 "MATNR",
	 "SPRAS")) UNLOAD PRIORITY 5 AUTO MERGE 
;
COMMENT ON TABLE "LIVE4"."MAKT" is 'Material Descriptions'
;
COMMENT ON COLUMN "LIVE4"."MAKT"."MANDT" is 'Client'
;
COMMENT ON COLUMN "LIVE4"."MAKT"."MATNR" is 'Material Number'
;
COMMENT ON COLUMN "LIVE4"."MAKT"."SPRAS" is 'Language Key'
;
COMMENT ON COLUMN "LIVE4"."MAKT"."MAKTX" is 'Material description'
;
COMMENT ON COLUMN "LIVE4"."MAKT"."MAKTG" is 'Material Description in Uppercase for Matchcodes'
;
