SET SCHEMA "LIVE4";

DROP TABLE "PAL_PARAMS";
DROP TYPE "PAL_T_DATA";
DROP TYPE "PAL_T_PARAMS";
DROP TYPE "PAL_T_COEFF";
DROP TYPE "PAL_T_FITTED";
DROP TYPE "PAL_T_SIGNIFICANCE";
DROP TYPE "PAL_T_PMML";
DROP TABLE "PAL_SIGNATURE";
DROP VIEW "PAL_DATA";
DROP TABLE "PAL_COEFF";
DROP TABLE "PAL_FITTED";
DROP TABLE "PAL_SIGNIFICANCE";
DROP TABLE "PAL_PMML";

CREATE TYPE "PAL_T_DATA" AS TABLE ("ID" INTEGER, "QUANTITY" INTEGER, "WERKS" INTEGER, "MATNR" INTEGER, "AQI" INTEGER, "TMP" INTEGER, "HUM" INTEGER);
CREATE TYPE "PAL_T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "PAL_T_COEFF" AS TABLE ("ID" INTEGER, "AI" DOUBLE);
CREATE TYPE "PAL_T_FITTED" AS TABLE ("ID" INTEGER, "FITTED" INTEGER);
CREATE TYPE "PAL_T_SIGNIFICANCE" AS TABLE ("NAME" VARCHAR(50), "VALUE" DOUBLE);
CREATE TYPE "PAL_T_PMML" AS TABLE ("ID" INTEGER, "PMML" VARCHAR(5000));

CREATE COLUMN TABLE "PAL_SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "PAL_SIGNATURE" VALUES (1, 'LIVE4', 'PAL_T_DATA', 'IN');
INSERT INTO "PAL_SIGNATURE" VALUES (2, 'LIVE4', 'PAL_T_PARAMS', 'IN');
INSERT INTO "PAL_SIGNATURE" VALUES (3, 'LIVE4', 'PAL_T_COEFF', 'OUT');
INSERT INTO "PAL_SIGNATURE" VALUES (4, 'LIVE4', 'PAL_T_FITTED', 'OUT');
INSERT INTO "PAL_SIGNATURE" VALUES (5, 'LIVE4', 'PAL_T_SIGNIFICANCE', 'OUT');
INSERT INTO "PAL_SIGNATURE" VALUES (6, 'LIVE4', 'PAL_T_PMML', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('LIVE4', 'PAL_MODEL');
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'EXPREGRESSION', 'LIVE4', 'PAL_MODEL', "PAL_SIGNATURE");

CREATE VIEW "PAL_DATA" AS
  SELECT "ROW_NUM" AS "ID", "QUANTITY", CAST("WERKS" AS INTEGER) AS "WERKS", CAST("MATNR" AS INTEGER) AS "MATNR", 
  		CAST(ROUND("AQI") AS INTEGER) AS "AQI", CAST(ROUND("TMP") AS INTEGER) AS "TMP", CAST(ROUND("HUM") AS INTEGER) AS "HUM"
   FROM "SALES_PER_LOCATION_PER_PRODUCT"
  ;

CREATE COLUMN TABLE "PAL_PARAMS" LIKE "PAL_T_PARAMS";

CREATE COLUMN TABLE "PAL_COEFF" LIKE "PAL_T_COEFF";
CREATE COLUMN TABLE "PAL_FITTED" LIKE "PAL_T_FITTED";
CREATE COLUMN TABLE "PAL_SIGNIFICANCE" LIKE "PAL_T_SIGNIFICANCE";
CREATE COLUMN TABLE "PAL_PMML" LIKE "PAL_T_PMML";

TRUNCATE TABLE "PAL_PARAMS";
INSERT INTO "PAL_PARAMS" VALUES ('PMML_EXPORT', 2, null, null);

TRUNCATE TABLE "PAL_COEFF";
TRUNCATE TABLE "PAL_FITTED";
TRUNCATE TABLE "PAL_SIGNIFICANCE";
TRUNCATE TABLE "PAL_PMML";
CALL "PAL_MODEL" ("PAL_DATA", "PAL_PARAMS", "PAL_COEFF", "PAL_FITTED", "PAL_SIGNIFICANCE", "PAL_PMML") WITH OVERVIEW;

SELECT * FROM "PAL_COEFF";
SELECT * FROM "PAL_FITTED" ORDER BY "FITTED" DESC;
SELECT * FROM "PAL_SIGNIFICANCE";
SELECT * FROM "PAL_PMML";
