SET SCHEMA "LIVE4";

DROP TYPE "PAL_T_P_DATA";
DROP VIEW "PAL_P_DATA";

CREATE TYPE "PAL_T_P_DATA" AS TABLE ("ID" INTEGER, "WERKS" INTEGER, "MATNR" INTEGER, "AQI" INTEGER, "TMP" INTEGER, "HUM" INTEGER);

TRUNCATE TABLE "PAL_SIGNATURE";
INSERT INTO "PAL_SIGNATURE" VALUES (1, 'LIVE4', 'PAL_T_P_DATA', 'IN');
INSERT INTO "PAL_SIGNATURE" VALUES (2, 'LIVE4', 'PAL_T_COEFF', 'IN');
INSERT INTO "PAL_SIGNATURE" VALUES (3, 'LIVE4', 'PAL_T_PARAMS', 'IN');
INSERT INTO "PAL_SIGNATURE" VALUES (4, 'LIVE4', 'PAL_T_FITTED', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('LIVE4', 'PAL_PREDICT');
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'FORECASTWITHEXPR', 'LIVE4', 'PAL_PREDICT', "PAL_SIGNATURE");

CREATE VIEW "PAL_P_DATA" AS
 SELECT "ROW_NUM" AS "ID", CAST(i."WERKS" AS INTEGER) AS "WERKS", CAST(i."MATNR" AS INTEGER) AS "MATNR", w."AQI", w."TMP", w."HUM"
  FROM "PRODUCT_INVENTORY" i
  INNER JOIN "T001W_WS" w ON (w."WERKS"=i."WERKS")
  ;

--TRUNCATE TABLE "PAL_PARAMS";

TRUNCATE TABLE "PAL_FITTED";

CALL "PAL_PREDICT" ("PAL_P_DATA", "PAL_COEFF", "PAL_PARAMS", "PAL_FITTED") WITH OVERVIEW;

SELECT * FROM "PAL_FITTED";

SELECT d."WERKS", d."MATNR", p."FITTED" 
 FROM "PAL_P_DATA" d
 INNER JOIN "PAL_FITTED" p ON (p."ID"=d."ID")
 ORDER BY p."FITTED" DESC
 ;
