SET SCHEMA "LIVE4";

DROP VIEW "PRODUCT_INVENTORY_PREDICTED";
CREATE VIEW "PRODUCT_INVENTORY_PREDICTED" AS
 SELECT i."WERKS", i."MATNR", m."MAKTX", ROUND(i."INVENTORY") AS "INVENTORY", ROUND(p."FITTED") AS "QUANTITY_PREDICTED", (ROUND(i."INVENTORY") - ROUND(p."FITTED")) AS "INVENTORY_PREDICTED_SPARE"
  FROM "PRODUCT_INVENTORY" i
  INNER JOIN "MAKT" m ON (m."MATNR"=i."MATNR")
  INNER JOIN "PAL_P_DATA" d ON (d."WERKS"=i."WERKS" AND d."MATNR"=i."MATNR")
  INNER JOIN "PAL_FITTED" p ON (p."ID"=d."ID")
  ;
  
SELECT * FROM "PRODUCT_INVENTORY_PREDICTED" ORDER BY "INVENTORY_PREDICTED_SPARE";
