-- run this as a HANA Administrator user

-- create the SAP_SPATIAL_POSTAL schema
CREATE SCHEMA SAP_SPATIAL_POSTAL;

-- grant access to the SAP_SPATIAL_POSTAL schema to the Live4 user
GRANT CREATE ANY, ALTER, DROP, EXECUTE, SELECT, INSERT, UPDATE, DELETE, INDEX, DEBUG, TRIGGER, REFERENCES ON SCHEMA SAP_SPATIAL_POSTAL TO LIVE4 WITH GRANT OPTION;
