-- RUN AS SYSTEM/ADMINISTRATOR USER

-- ENABLE HANA NATIVE DEVELOPMENT
GRANT EXECUTE ON REPOSITORY_REST TO LIVE4;
GRANT REPO.READ, REPO.EDIT_NATIVE_OBJECTS, REPO.ACTIVATE_NATIVE_OBJECTS, REPO.MAINTAIN_NATIVE_PACKAGES ON ".REPO_PACKAGE_ROOT" TO LIVE4;

-- WEB DEVELOPMENT WORKBENCH
CALL GRANT_ACTIVATED_ROLE('sap.hana.ide.roles::Developer','LIVE4');

-- LIVE4 APP
--CALL GRANT_APPLICATION_PRIVILEGE ('"live4::Execute"','LIVE4');
